### ISSUE TITLE
ephysview example not working

### ISSUE THREAD

**Issue by guidomeijer** [datoviz/prototypes#1]
I was just trying to run the ephysview example (like so: `python ephysview.py f25642c6-27a5-4a97-9ea0-06652db79fbd 0`) but am getting the following error:
```
16:55:21.112 I          ephysview:0616: Apply filter default
Traceback (most recent call last):
  File "ephysview.py", line 825, in <module>
    ctrl = Controller(m, rv, ev)
  File "ephysview.py", line 469, in __init__
    self.set_range(0, .1)
  File "ephysview.py", line 557, in set_range
    self.ev.show_spikes(times, depths, colors)
  File "ephysview.py", line 414, in show_spikes
    self.v_spikes.data('marker', np.array([5]))  # HACK: cross marker
  File "datoviz/pydatoviz.pyx", line 1314, in datoviz.pydatoviz.Visual.data
  File "datoviz/pydatoviz.pyx", line 439, in datoviz.pydatoviz._get_prop
KeyError: 'marker'
```
I installed datoviz according to the instructions, the example is running. I also pulled the latest changes of the ibllib develop branch. Any help would be appreciated!

**Comment by rossant** [comment]
This is due to today's changes to the viewer code involving changes in Datoviz which are not yet part of the prebuilt packages. I'll make new packages soon, but in the meantime, if are you're able to build Datoviz from source (relatively straightforward on Ubuntu if that's what you use?), that might work?

**Comment by rossant** [comment]
Otherwise you can try to pull the latest commit on this prototypes repo, I think I removed the bits that depend on the latest changes to Datoviz.

**Comment by guidomeijer** [comment]
Thanks! Pulling the latest changes of the prototypes repo worked :)
